{% set name = "flask-apispec" %}
{% set version = "0.8.6" %}
{% set sha256 = "9116681983a30255dfee05f74a2ef13f9bc56326dc9bffc4024f61fc555b0cdb" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python
    - pip
  run:
    - python
    - six >=1.9.0
    - flask >=0.10.1
    - marshmallow >=2.0.0
    - webargs >=0.18.0
    - apispec >=1.0.0

test:
  imports:
    - flask_apispec

about:
  home: https://github.com/jmcarp/flask-apispec
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Build and document REST APIs with Flask and apispec

  description: |
    flask-apispec is a lightweight tool for building REST APIs in Flask. 
    flask-apispec uses webargs for request parsing, marshmallow for response
    formatting, and apispec to automatically generate Swagger markup.
    You can use flask-apispec with vanilla Flask or a fuller-featured
    framework like Flask-RESTful.
  doc_url: https://flask-apispec.readthedocs.org/en/latest/
  dev_url: https://github.com/jmcarp/flask-apispec

extra:
  recipe-maintainers:
    - rth
    - synapticarbors
