{% set name = "flask-apispec" %}
{% set version = "0.8.0" %}
{% set sha256 = "04a5e8f53db88953a9725f37f6a0da7d61ffcd36f43c078b149336460fe7d1be" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - setuptools
    - pip
  run:
    - python
    - six >=1.9.0
    - flask >=0.10.1
    - marshmallow >=2.0.0
    - webargs >=0.18.0
    - apispec >=0.17.0

test:
  imports:
    - flask_apispec

about:
  home: https://github.com/jmcarp/flask-apispec
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Build and document REST APIs with Flask and apispec'

  description: |
      flask-apispec is a lightweight tool for building REST APIs in Flask. 
      flask-apispec uses webargs for request parsing, marshmallow for response
      formatting, and apispec to automatically generate Swagger markup.
      You can use flask-apispec with vanilla Flask or a fuller-featured
      framework like Flask-RESTful.
  doc_url: https://flask-apispec.readthedocs.org/en/latest/
  dev_url: https://github.com/jmcarp/flask-apispec

extra:
  recipe-maintainers:
    - rth
    - synapticarbors
