travis:
  secure:
    BINSTAR_TOKEN: cRqsb/YyNNUMSNgVR+pRTIK/XLj1p7O9zvuvB2SCYa78PZJ5EVlY5uvI5+MvxOgwQWXuc5/RnLMmEy9oLiM4ikUPNrDeugR6kGW440HrsOgxs6Y2PcMD2G3xvfFYDi2+u0YdL83l42+vhCIAFXk/ouwJp/kN27IpuO/1Tx9GewCOWwiU5uWWKNAGgW2Zb0RsUGFLGpD/p25Wu6IFyHjM1c8MbEsYoPevETh+30PdCOKqXMtFO3p2s1dOYwMFn/JqDjey6oH4MPy14/k6y1x1x1trbYEcb/sAs11AjhfN0lDmmU0Bn9lTi3lrE2myWacpwIDG0xd8w3Z0YB3kWOHPayVcRfcErUey93XOJg3upT65Zo7GFEP+iEydELJ/zRLygQdj0Ia33OjgRxForTjjTXY9KYpj9i1ZL/tqpfdjvIsIyF6uUmCLjSWZuDJnX4BG2zjixBZvexYTry3Hw9/EOyq4cf2kaiT27O7wFqgBM1T1fyRybraStVW4r72uwQckuiOOzVSvkv9REY2g+sI3D92qK07/RFz3WIpX2Uc64GSylE8CMXFR1Gn0vpeifyPXTMN7uiWOY8ARyaiZPueuJKaDizIIs9owq/gsrmEaIPUqok6KqTUG0dxffqo450c3+Gzp+3l4gE2yPCluotBTNDgmbdHavFQ0RQ9ciWqyKz8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
