travis:
  secure:
    BINSTAR_TOKEN: YcXdiCEGn1VMg2Bciydk5frb9U4dqaGRKeK7z7MKjSjXCkp8obJCwe/b0PxTrTqDo0NmfotuJtja0dLV9THolMS6iQRTa0PqQPIqHvAomEBX+qfn5D+F9cLqA2OyWP9tVpdqY2EFqZ+cRLECFVZoBKzGxbo9in80RwXCsSxsd2YYR6BGk7MpNMlm+rKZw3xHwH7gLb35Nst8ljPQCh9GJPhqPxSkJ7SXD/O/kDqmrBqTibT6fR7K0pkjP9+HcsQ8IDA4NgYo9IlJI/A+MfngIBL4gx1SxmW2Guj8o9j9vta9Pu6VSm0Ya0wg6cArGRedM1tiKOnsW9pPohkPihda7LZ5gn8z81VTwLgkTU4kg+kdqYjGsNUsKAanAAVzs1eIIcJ+Mj77w9cGFC6KSESrdJUE8ZTTUiImQlgAOEsalMLRujWNMwxgZNBCxR0MXsGdZE3uolKmciqmrsysDvwgBv0YlIhRM1p4lAX6eTmhAk067YJYVemwssn3VDZVN/zBjovzRvAZW5nODmnL75XlvaSJsLvHWXXT82Q9dCg2pK+CeaFsrFVNTddAf66evDXUlTpizrF+kak7wve9S/j/0RPa+V7hbcVSSsn/hzXOorE8s8J3RIk6CfbQFGnTRJb3t7+omVXDPbpTA0uw6IDq1bK0FWUFD7jqR3RDKMdoZYU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
