travis:
  secure:
    BINSTAR_TOKEN: quv9d2tlDdnHrZ3j+7K5BBW3GR00YiKaYbcEcr9KvF+gn9opy/8NJ4cpqjrNy4duzdwfOfTGKDPBoT6bqDsc4Um2JN0B7nntPO9ZWTl+gKUoK8EBbSVMMsW6eM52yyrUOCAqDs48JMT9Ar+QiH37+29KvUw73Hy6rmalEQXEpt6lHhnHPb2cUNsiRquEy8QSEATH0f5P9ro11XQve+hfLrBtZ8u8n3g+4djUmmJCpRx2U0errm6dGz0FcRuQavqLgRjg7M/uD3BCT/OAoWRAM44M523rVqoqi702qZrifKXBB0Lz08bwX3AqbPv6lSF9u37qByna3iroKx+edY9xnqVkymwVaKVyFUHJor+cUQfoQl9UsFCbZjMMET7lhGjBPwW+QJ5ZVCZ9pBa9wg5wMnRxkwTHK3TVj3OPUw9dZNmoPkyS5aNRxobl/CUaUykvycRWQbcy6OIEAyRQHsZz8PALoDCf3gEMPFIk59fFJ2E8BjlehuM5k+p2GGBnFfUhFK5AK+dnCIhWYnOyB/ypZpqczBJAVesrYjxuZvQCsn+9Y3PaNSQBv65EY7bAaxzWMxBzqagiEbJ3W7DkDUGjWY9S3p6zC6e/xTRl+IWaiVJCWFqdWIGxefDYFm2jw9El0KqBI1ON6OT9OpIK1xr6b7XMQbSxWDV92GljNQIORHI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
